# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-06 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_start', models.DateTimeField(db_index=True, null=True)),
                ('home_team', models.CharField(db_index=True, max_length=1024)),
                ('away_team', models.CharField(db_index=True, max_length=1024)),
                ('league', models.CharField(db_index=True, max_length=1024, null=True)),
                ('current_home_goals', models.IntegerField(null=True)),
                ('current_away_goals', models.IntegerField(null=True)),
                ('asian_handicap', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('asian_handicap_home_odds', models.FloatField(null=True)),
                ('asian_handicap_away_odds', models.FloatField(null=True)),
                ('total_line', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('total_line_over', models.FloatField(null=True)),
                ('total_line_under', models.FloatField(null=True)),
            ],
        ),
    ]
