# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b365dapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstate',
            name='attacks_away',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='eventstate',
            name='attacks_home',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='eventstate',
            name='dangerous_attacks_away',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='eventstate',
            name='dangerous_attacks_home',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='eventstate',
            name='possession_away',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='eventstate',
            name='possession_home',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='eventstate',
            name='shots_off_target_away',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='eventstate',
            name='shots_off_target_home',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='eventstate',
            name='shots_on_target_away',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='eventstate',
            name='shots_on_target_home',
            field=models.IntegerField(null=True),
        ),
    ]
