# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b365dapp', '0002_auto_20180421_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='currenteventstate',
            name='match_minutes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='currenteventstate',
            name='match_seconds',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='eventstate',
            name='match_minutes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='eventstate',
            name='match_seconds',
            field=models.IntegerField(null=True),
        ),
    ]
