# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b365dapp', '0002_auto_20180411_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstate',
            name='corners_away',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='eventstate',
            name='corners_home',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='eventstate',
            name='red_cards_away',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='eventstate',
            name='red_cards_home',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='eventstate',
            name='yellow_cards_away',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='eventstate',
            name='yellow_cards_home',
            field=models.IntegerField(null=True),
        ),
    ]
