# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('b365dapp', '0003_auto_20180411_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventstate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Event State', 'verbose_name_plural': 'Event States'},
        ),
        migrations.AddField(
            model_name='eventstate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
