# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-13 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b365dapp', '0005_eventstate_game_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentEventState',
            fields=[
                ('eventstate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='b365dapp.EventState')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Current Event State',
                'verbose_name_plural': 'Current Event States',
            },
            bases=('b365dapp.eventstate',),
        ),
    ]
