# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-13 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b365dapp', '0008_auto_20180413_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventstate',
            name='first_asian_handicap',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='eventstate',
            name='first_asian_handicap_away_odds',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='eventstate',
            name='first_asian_handicap_home_odds',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='eventstate',
            name='first_total_line',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='eventstate',
            name='first_total_line_over',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='eventstate',
            name='first_total_line_under',
            field=models.FloatField(null=True),
        ),
    ]
